#!/usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = "Evangelos A. Dimopoulos"
__copyright__ = "Copyright 2021, University of Oxford"
__email__ = "antonisdim41@gmail.com"
__license__ = "MIT"


include: "rules/adapterremoval.smk"
include: "rules/qc.smk"
include: "rules/clustering.smk"
include: "rules/assembly.smk"


rule all:
    input:
        # "qc/fastqc_summary.tsv",
        # "poppunk_ecoli/qfile.txt",
        "assemblies.done"
