#!/usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = "Evangelos A. Dimopoulos"
__copyright__ = "Copyright 2021, University of Oxford"
__email__ = "antonisdim41@gmail.com"
__license__ = "MIT"

import os

from scripts.utilities import REF_GENOME_TABLE, OUT_GENOME_TABLE


include: "rules/adapterremoval.smk"
include: "rules/qc.smk"
include: "rules/clustering.smk"
include: "rules/assembly.smk"
include: "rules/mlst.smk"
include: "rules/annotation.smk"
include: "rules/pangenome.smk"
include: "rules/amr.smk"


if os.path.isfile(REF_GENOME_TABLE):

    include: "rules/bt2_aln.smk"
    include: "rules/htsbox.smk"
    include: "rules/seq_stats.smk"
    include: "rules/trees.smk"
    include: "rules/snp_calling.smk"
    include: "rules/serotyping.smk"


if os.path.isfile(OUT_GENOME_TABLE):

    include: "rules/outgroup.smk"
    include: "rules/tree_stats.smk"
    include: "rules/muttui.smk"


rule all:
    input:
        # "qc/fastqc_summary.tsv",
        # "assemblies.done",
        # "assemblies/assemblies_stats_ecoli.tsv",
        # "panaroo_ecoli/pangenome_merged/pan_genome_reference.fa",
        # "panaroo_ecoli/pangenome_merged/core_gene_alignment.aln",
        # "panaroo_ecoli/pangenome_merged/snps_core_gene_alignment.aln",
        # "clustering_ecoli/summary_clusters_mlst_ecoli_plus_contx.tsv",
        # expand("seqs_ecoli/ecoli_cluster_{num}_seq_summary.tsv", num=[21, 23, 16, 19, 14, 2, 8, 10, 18, 13, 28, 20, 27, 24, 7, 3, 11, 29]),
        # expand("gatk_ecoli/ecoli_cluster_{num}_SNP_filter_table.tsv", num=[21, 23, 16, 19, 14, 2, 8, 10, 18, 13, 28, 20, 27, 24, 7, 3, 11, 29]),
        # expand("gatk_ecoli/ecoli_cluster_{num}_sfs.pdf", num=[21, 23, 16, 19, 14, 2, 8, 10, 18, 13, 28, 20, 27, 24, 7, 3, 11, 29]),
        # expand(
        #     "trees_ecoli/ecoli_cluster_{num}_iq.treefile",
        #     num=[21, 23, 16, 19, 14, 2, 8, 10, 18, 13, 28, 20, 27, 24, 7, 3, 11, 29],
        # ),
        # "trees_ecoli/ecoli_population_21_iq.treefile",
        # "aux_files/github_r.done",
        # "trees_stats_ecoli/ecoli_cluster_tree_stats.tsv",
        # "trees_stats_ecoli/ecoli_population_21_total_host_links.tsv",
        # expand(
        #     "muttui_ecoli/ecoli_cluster_{num}/all_included_mutations.csv",
        #     num=[21, 23, 16, 19, 14, 2, 8, 10, 18, 13, 28, 20, 27, 24, 7, 3, 11, 29],
        # ),
        # expand(
        #     "muttui_ecoli/ecoli_cluster_{num}_label/all_included_mutations.csv",
        #     num=[21, 23, 16, 19, 14, 2, 8, 10, 18, 13, 28, 20, 27, 24, 7, 3, 11, 29],
        # ),
        # expand(
        #     "ariba_card_ecoli/ecoli_cluster_{num}_report.csv",
        #     num=[21, 23, 16, 19, 14, 2, 8, 10, 18, 13, 28, 20, 27, 24, 7, 3, 11, 29],
        # ),
        # expand(
        #     "ariba_vfdb_core_ecoli/ecoli_cluster_{num}_report.csv",
        #     num=[21, 23, 16, 19, 14, 2, 8, 10, 18, 13, 28, 20, 27, 24, 7, 3, 11, 29],
        # ),
        # expand(
        #     "abricate_card_ecoli/ecoli_cluster_{num}_report.tsv",
        #     num=[21, 23, 16, 19, 14, 2, 8, 10, 18, 13, 28, 20, 27, 24, 7, 3, 11, 29],
        # ),
        # expand(
        #     "abricate_vfdb_ecoli/ecoli_cluster_{num}_report.tsv",
        #     num=[21, 23, 16, 19, 14, 2, 8, 10, 18, 13, 28, 20, 27, 24, 7, 3, 11, 29],
        # ),
        # "ariba_card_ecoli/ecoli_population_21_report.csv",
        # "serotyping_ecoli/ecoli_population_21_sero_report.tsv",
        # "gatk_ecoli/ecoli_cluster_1000_SNP_filter_table.tsv",
        # "gatk_ecoli/ecoli_cluster_1000_sfs.pdf",
        # "panaroo_campylobacter/pangenome_merged/snps_core_gene_alignment.aln",
        "trees_stats_campylobacter/campylobacter_cluster_tree_stats.tsv",
        # expand(
        #     "trees_stats_campylobacter/campylobacter_cluster_{num}_cohort_hist.pdf",
        #     num=[1, 2, 4, 5, 6, 7, 8],
        # ),
